"""Browser route types — ported from bk/src/browser/routes/types.ts."""
from __future__ import annotations

from typing import Any, Callable, Protocol


class BrowserRouteContext(Protocol):
    def get_state(self) -> Any: ...
    def get_resolved_config(self) -> Any: ...


class BrowserRouteRegistrar(Protocol):
    def get(self, path: str, handler: Callable[..., Any]) -> None: ...
    def post(self, path: str, handler: Callable[..., Any]) -> None: ...
    def delete(self, path: str, handler: Callable[..., Any]) -> None: ...
