"""Browser constants — ported from bk/src/browser/constants.ts."""

DEFAULT_COLARCORE_BROWSER_ENABLED = True
DEFAULT_BROWSER_EVALUATE_ENABLED = True
DEFAULT_COLARCORE_BROWSER_COLOR = "#FF4500"
DEFAULT_COLARCORE_BROWSER_PROFILE_NAME = "colarcore"
DEFAULT_BROWSER_DEFAULT_PROFILE_NAME = "colarcore"
DEFAULT_AI_SNAPSHOT_MAX_CHARS = 80_000
DEFAULT_AI_SNAPSHOT_EFFICIENT_MAX_CHARS = 10_000
DEFAULT_AI_SNAPSHOT_EFFICIENT_DEPTH = 6
