"""Channels plugins.agent_tools — ported from bk/src/channels/plugins/agent-tools/whatsapp-login.ts.

Agent tools for channel operations (WhatsApp login QR refresh, etc.).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass
class WhatsAppLoginToolResult:
    success: bool = False
    qr_code: str = ""
    message: str = ""


async def handle_whatsapp_login_tool(
    cfg: dict[str, Any],
    account_id: str = "",
) -> WhatsAppLoginToolResult:
    """Handle the WhatsApp login agent tool (QR code generation).

    In the full implementation this would interact with the WhatsApp
    Web session to generate a new QR code for linking.
    """
    return WhatsAppLoginToolResult(
        success=True,
        message="WhatsApp login tool invoked. QR code would be generated by the gateway.",
    )


# ─── web/index.ts ───

def get_web_channel_config(cfg: dict[str, Any]) -> dict[str, Any]:
    """Get web channel configuration."""
    return cfg.get("channels", {}).get("web", {})


def is_web_channel_enabled(cfg: dict[str, Any]) -> bool:
    """Check if the web channel is enabled."""
    web_cfg = get_web_channel_config(cfg)
    return web_cfg.get("enabled", False)
